# Model Training Framework 1 
#### Code for training three model architectures.

In [1]:
# Import necessary modules
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import os
from os import listdir
from os.path import isfile, join
from PIL import Image
import keras
from keras import layers
import csv
from tensorflow.keras.utils import to_categorical

2025-10-30 18:32:03.993888: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1761849124.414945      37 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1761849124.547382      37 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered

In [2]:
# Read the data set 
eda = pd.read_csv('train_labels.csv')
eda

                                              id  label
0       f38a6374c348f90b587e046aac6079959adf3835      0
1       c18f2d887b7ae4f6742ee445113fa1aef383ed77      1
2       755db6279dae599ebb4d39a9123cce439965282d      0
3       bc3f0c64fb968ff4a8bd33af6971ecae77c75e08      0
4       068aba587a4950175d04c680d38943fd488d6a9d      0
...                                          ...    ...
220020  53e9aa9d46e720bf3c6a7528d1fca3ba6e2e49f6      0
220021  d4b854fe38b07fe2831ad73892b3cec877689576      1
220022  3d046cead1a2a5cbe00b2b4847cfb7ba7cf5fe75      0
220023  f129691c13433f66e1e0671ff1fe80944816f5a2      0
220024  a81f84895ddcd522302ddf34be02eb1b3e5af1cb      1

[220025 rows x 2 columns]

In [3]:
# Function to select a train set sample, because the 0/1 division is 60/40
# the sample is stratified this way
def sub_sample(frac_):
    zero_sample = int(len(eda)*frac_*0.6)
    eda_zero = eda[eda.label == 0]
    sample_eda_zero = eda_zero.sample(n = zero_sample, replace=False, random_state=52)

    # A sub sample of only one labels  
    one_sample = int(len(eda)*frac_*0.4)
    eda_one = eda[eda.label == 1]
    sample_eda_one = eda_one.sample(n = one_sample, replace=False, random_state=52)

    # Merge the sample data sets 
    frames = [sample_eda_zero, sample_eda_one]
    train_df = pd.concat(frames)

    train_df = train_df.sample(frac=1, random_state = 126)
    
    return train_df

In [4]:
# Apply sub_sample function
train_df = sub_sample(0.1)
train_df

                                              id  label
176288  1d122a55476973f3847a705c96817c1e1b5ede9d      0
155346  5d94c8b0f0645c894c0ffcb292bbceb70393ea20      0
48863   d505c8b4fc7d65596ff3a8e6197b3a2474b68371      0
175558  11f7a527b4cabfcc4d00b455c9ecb52fc0547feb      1
195137  36ddfecad2e2b330e7bc8ba8fde52ddd2300168e      0
...                                          ...    ...
177151  db01a27193d200bc6d626f22d40fa2a441ebe082      1
211211  b3ed317e4997ad9435d2a8f9aeddcdb16fff079f      0
28330   f2552d8e74f0c4ccead7af168b9c3d5e2ce94bce      0
5173    112e7f5aff9bb19cfe15e8646ba6a5bcf7dbe4fd      0
1381    b9192a8a510742d683eb28be48f62d536d069795      0

[22002 rows x 2 columns]

In [5]:
# Function to transform .tif file to an array and to one hot encode the label 
def to_array(train_df = train_df):

    # String of working directory
    train_dir = '/kaggle/input/histopathologic-cancer-detection/train'
    
    imarray_totaal = []
    # Loop to import training images n train_df (by file names) from working directory
    for j in train_df.id:
    
        im = Image.open(train_dir + '/' + j + '.tif')
        # Turn '.tif' file into array
        imarray = np.array(im)
        
        imarray_totaal.append(imarray)
    
    # Turn list into array
    imarray_totaal= np.array(imarray_totaal)
    
    # One hot encoding for the label: Turning one label (0/1) into two labels (Label_0 and Label_1) 
    num_classes = 2
    labels = to_categorical(train_df.label, num_classes=num_classes)
    
    # Giving imarray_totaal (x_train) and labels (y_train) familiar names 
    x_train = imarray_totaal
    y_train = labels

    return x_train, y_train

In [6]:
# Function to write model training results to an external location 
def write_away(name, model_results, path):

# Writing away the results 
    name = pd.DataFrame.from_dict(model_results)
    name.to_csv(path, index=False)
    return name

In [7]:
# Apply to_array
train_set = to_array()
x_train = train_set[0]
y_train = train_set[1]

### Model 1

In [8]:
num_classes = 2
input_shape = (96, 96, 3)

model = keras.Sequential(
    [keras.Input(shape = input_shape),
     layers.Conv2D(filters = 32, kernel_size=(3,3),activation = 'sigmoid'),
     layers.MaxPooling2D(pool_size=(2, 2)),
     layers.Flatten(),
     layers.Dense(num_classes, activation="softmax"),
    ]
    )
model.summary()

I0000 00:00:1761849509.231279      37 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 13942 MB memory:  -> device: 0, name: Tesla T4, pci bus id: 0000:00:04.0, compute capability: 7.5
I0000 00:00:1761849509.231985      37 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 13942 MB memory:  -> device: 1, name: Tesla T4, pci bus id: 0000:00:05.0, compute capability: 7.5

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 94, 94, 32)     │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 47, 47, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 70688)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 2)              │       141,378 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 142,274 (555.76 KB)

 Trainable params: 142,274 (555.76 KB)

 Non-trainable params: 0 (0.00 B)

In [9]:
# training model 1
batch_size = 200
epochs = 20
model.compile(loss="categorical_crossentropy", optimizer="sgd", metrics=["accuracy", "auc"])

history = model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.1)

Epoch 1/20

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1761849521.214682     101 service.cc:148] XLA service 0x7aa698007300 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1761849521.215851     101 service.cc:156]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
I0000 00:00:1761849521.215873     101 service.cc:156]   StreamExecutor device (1): Tesla T4, Compute Capability 7.5
I0000 00:00:1761849521.453288     101 cuda_dnn.cc:529] Loaded cuDNN version 90300

  7/100 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.4988 - auc: 0.5371 - loss: 19.6773

I0000 00:00:1761849524.771472     101 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

100/100 ━━━━━━━━━━━━━━━━━━━━ 9s 46ms/step - accuracy: 0.5158 - auc: 0.5267 - loss: 25.8441 - val_accuracy: 0.6025 - val_auc: 0.6025 - val_loss: 41.0164
Epoch 2/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - accuracy: 0.5297 - auc: 0.5282 - loss: 25.9764 - val_accuracy: 0.6025 - val_auc: 0.6025 - val_loss: 42.5910
Epoch 3/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 2s 23ms/step - accuracy: 0.5301 - auc: 0.5301 - loss: 24.1625 - val_accuracy: 0.6025 - val_auc: 0.6025 - val_loss: 20.5835
Epoch 4/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.5220 - auc: 0.5231 - loss: 20.3982 - val_accuracy: 0.6025 - val_auc: 0.6025 - val_loss: 47.2044
Epoch 5/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.5278 - auc: 0.5270 - loss: 21.6627 - val_accuracy: 0.6025 - val_auc: 0.6025 - val_loss: 27.5774
Epoch 6/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.5291 - auc: 0.5354 - loss: 20.5417 - val_accuracy: 0.3975 - val_auc: 0.3975 - val_loss: 42.7931
Epoch 7/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.5248 - auc: 0.5259 - loss: 20.1729 - val_accuracy: 0.6025 - val_auc: 0.6025 - val_loss: 28.5521
Epoch 8/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.5406 - auc: 0.5441 - loss: 18.6216 - val_accuracy: 0.3975 - val_auc: 0.3975 - val_loss: 58.7873
Epoch 9/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.5126 - auc: 0.5136 - loss: 32.2456 - val_accuracy: 0.6025 - val_auc: 0.6025 - val_loss: 32.0178
Epoch 10/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - accuracy: 0.5291 - auc: 0.5323 - loss: 25.2879 - val_accuracy: 0.4107 - val_auc: 0.4121 - val_loss: 17.3592
Epoch 11/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.5568 - auc: 0.5586 - loss: 20.1826 - val_accuracy: 0.6025 - val_auc: 0.6025 - val_loss: 59.4162
Epoch 12/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.5327 - auc: 0.5382 - loss: 25.2318 - val_accuracy: 0.6006 - val_auc: 0.6066 - val_loss: 2.4262
Epoch 13/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.5470 - auc: 0.5493 - loss: 21.1279 - val_accuracy: 0.6025 - val_auc: 0.6025 - val_loss: 132.1747
Epoch 14/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.5477 - auc: 0.5490 - loss: 28.5634 - val_accuracy: 0.6025 - val_auc: 0.6025 - val_loss: 52.9966
Epoch 15/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.5521 - auc: 0.5561 - loss: 19.9483 - val_accuracy: 0.3975 - val_auc: 0.3975 - val_loss: 62.4720
Epoch 16/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.5519 - auc: 0.5503 - loss: 18.2533 - val_accuracy: 0.5388 - val_auc: 0.6264 - val_loss: 2.0495
Epoch 17/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.5451 - auc: 0.5553 - loss: 15.1414 - val_accuracy: 0.3975 - val_auc: 0.3975 - val_loss: 63.8144
Epoch 18/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.5457 - auc: 0.5488 - loss: 18.0088 - val_accuracy: 0.6006 - val_auc: 0.6413 - val_loss: 2.2684
Epoch 19/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.5675 - auc: 0.5732 - loss: 14.1674 - val_accuracy: 0.6025 - val_auc: 0.6025 - val_loss: 38.6503
Epoch 20/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.5638 - auc: 0.5711 - loss: 12.9089 - val_accuracy: 0.6025 - val_auc: 0.6025 - val_loss: 8.9860

In [11]:
# Model 1: Writing away the results 
write_away('Simple_CNN', history.history, 'Simple_CNN.csv')

    accuracy       auc       loss  val_accuracy   val_auc    val_loss
0   0.515984  0.519213  26.532612      0.602453  0.602453   41.016365
1   0.522953  0.521891  25.784670      0.602453  0.602453   42.590958
2   0.523155  0.523769  22.092428      0.602453  0.602453   20.583513
3   0.525933  0.528947  20.064478      0.602453  0.602453   47.204380
4   0.524569  0.524511  20.616272      0.602453  0.602453   27.577425
5   0.525782  0.528600  20.394987      0.397547  0.397547   42.793072
6   0.530882  0.532719  19.369314      0.602453  0.602453   28.552139
7   0.538710  0.540832  18.400537      0.397547  0.397547   58.787315
8   0.523256  0.524442  30.518532      0.602453  0.602453   32.017765
9   0.536034  0.539475  23.344458      0.410722  0.412143   17.359217
10  0.553810  0.556568  20.679655      0.602453  0.602453   59.416164
11  0.544720  0.549922  22.130075      0.600636  0.606627    2.426158
12  0.549215  0.551956  21.110823      0.602453  0.602453  132.174698
13  0.549467  0.550850  22.949642      0.602453  0.602453   52.996632
14  0.552144  0.556943  17.139011      0.397547  0.397547   62.472050
15  0.559315  0.561285  16.472061      0.538846  0.626434    2.049500
16  0.555628  0.562796  15.281910      0.397547  0.397547   63.814430
17  0.553406  0.557564  16.123356      0.600636  0.641316    2.268390
18  0.564820  0.571240  13.416469      0.602453  0.602453   38.650291
19  0.563002  0.570343  11.758575      0.602453  0.602453    8.985990

### Model 2

In [12]:
num_classes = 2
input_shape = (96, 96, 3)

model1 = keras.Sequential(
    [keras.Input(shape = input_shape),
     layers.Conv2D(filters = 32, kernel_size=(3,3),activation = 'sigmoid'),
     layers.MaxPooling2D(pool_size=(2, 2)),
     layers.Conv2D(64, kernel_size=(3, 3), activation="sigmoid"),
     layers.MaxPooling2D(pool_size=(2, 2)),
     layers.Flatten(),
     layers.Dense(num_classes, activation="softmax"),
    ]
    )
model1.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_1 (Conv2D)               │ (None, 94, 94, 32)     │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 47, 47, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 45, 45, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_2 (MaxPooling2D)  │ (None, 22, 22, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ (None, 30976)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 2)              │        61,954 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 81,346 (317.76 KB)

 Trainable params: 81,346 (317.76 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
# training model 2
batch_size = 200
epochs = 20

model1.compile(loss="categorical_crossentropy", optimizer="sgd", metrics=["accuracy", "auc"])

history1 = model1.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.1)

Epoch 1/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 10s 65ms/step - accuracy: 0.5314 - auc: 0.5396 - loss: 4.8377 - val_accuracy: 0.3975 - val_auc: 0.3974 - val_loss: 2.3823
Epoch 2/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.5401 - auc: 0.5620 - loss: 0.7848 - val_accuracy: 0.6025 - val_auc: 0.6039 - val_loss: 1.2250
Epoch 3/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 36ms/step - accuracy: 0.5964 - auc: 0.6033 - loss: 0.7077 - val_accuracy: 0.3975 - val_auc: 0.3881 - val_loss: 2.0897
Epoch 4/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 36ms/step - accuracy: 0.5850 - auc: 0.5801 - loss: 0.7508 - val_accuracy: 0.6025 - val_auc: 0.6582 - val_loss: 1.2201
Epoch 5/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.5956 - auc: 0.6022 - loss: 0.7128 - val_accuracy: 0.3975 - val_auc: 0.3566 - val_loss: 1.8771
Epoch 6/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.5803 - auc: 0.5875 - loss: 0.7279 - val_accuracy: 0.6025 - val_auc: 0.6624 - val_loss: 1.0971
Epoch 7/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.6016 - auc: 0.6072 - loss: 0.6953 - val_accuracy: 0.6025 - val_auc: 0.6642 - val_loss: 1.0968
Epoch 8/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.5925 - auc: 0.5971 - loss: 0.7028 - val_accuracy: 0.6025 - val_auc: 0.6579 - val_loss: 1.0654
Epoch 9/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.6027 - auc: 0.6099 - loss: 0.6972 - val_accuracy: 0.6025 - val_auc: 0.6676 - val_loss: 1.0505
Epoch 10/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.6031 - auc: 0.6153 - loss: 0.6887 - val_accuracy: 0.6025 - val_auc: 0.7268 - val_loss: 1.1293
Epoch 11/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.5980 - auc: 0.6184 - loss: 0.6963 - val_accuracy: 0.6025 - val_auc: 0.6425 - val_loss: 1.0344
Epoch 12/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.6054 - auc: 0.6251 - loss: 0.6844 - val_accuracy: 0.6025 - val_auc: 0.6362 - val_loss: 1.0690
Epoch 13/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.5963 - auc: 0.6263 - loss: 0.6852 - val_accuracy: 0.3975 - val_auc: 0.4671 - val_loss: 1.5060
Epoch 14/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.5928 - auc: 0.6268 - loss: 0.7034 - val_accuracy: 0.6025 - val_auc: 0.6290 - val_loss: 1.2004
Epoch 15/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.5797 - auc: 0.6228 - loss: 0.6966 - val_accuracy: 0.6025 - val_auc: 0.6313 - val_loss: 1.2371
Epoch 16/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.5884 - auc: 0.6358 - loss: 0.6908 - val_accuracy: 0.6025 - val_auc: 0.6473 - val_loss: 1.4483
Epoch 17/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - accuracy: 0.5981 - auc: 0.6460 - loss: 0.7081 - val_accuracy: 0.6025 - val_auc: 0.6752 - val_loss: 1.3945
Epoch 18/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - accuracy: 0.6533 - auc: 0.7033 - loss: 0.6527 - val_accuracy: 0.6025 - val_auc: 0.6778 - val_loss: 1.7185
Epoch 19/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - accuracy: 0.5778 - auc: 0.6537 - loss: 0.6844 - val_accuracy: 0.6025 - val_auc: 0.6460 - val_loss: 1.1602
Epoch 20/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - accuracy: 0.5682 - auc: 0.6077 - loss: 0.7413 - val_accuracy: 0.6025 - val_auc: 0.6025 - val_loss: 2.4119

In [14]:
# Model 2: Writing away the results 
write_away('Basic_CNN', history1.history, 'Basic_CNN.csv')

    accuracy       auc      loss  val_accuracy   val_auc  val_loss
0   0.522903  0.537365  2.418547      0.397547  0.397366  2.382312
1   0.551285  0.575359  0.714407      0.602453  0.603898  1.224959
2   0.586890  0.598062  0.687219      0.397547  0.388072  2.089719
3   0.585778  0.591295  0.695997      0.602453  0.658151  1.220074
4   0.593152  0.602870  0.684799      0.397547  0.356619  1.877133
5   0.592344  0.598123  0.687036      0.602453  0.662376  1.097071
6   0.599616  0.601541  0.680755      0.602453  0.664198  1.096807
7   0.596889  0.600806  0.681332      0.602453  0.657897  1.065437
8   0.599465  0.605328  0.679700      0.602453  0.667640  1.050527
9   0.597697  0.617880  0.674912      0.602453  0.726846  1.129296
10  0.597142  0.617379  0.676152      0.602453  0.642548  1.034434
11  0.598606  0.625205  0.671813      0.602453  0.636204  1.068976
12  0.600727  0.638695  0.666117      0.397547  0.467106  1.505963
13  0.598253  0.634216  0.671047      0.602453  0.629030  1.200395
14  0.583203  0.627380  0.677128      0.602453  0.631285  1.237092
15  0.587799  0.634746  0.672060      0.602453  0.647281  1.448320
16  0.602343  0.647312  0.674954      0.602453  0.675223  1.394450
17  0.648907  0.695403  0.642061      0.602453  0.677783  1.718548
18  0.589768  0.662883  0.647216      0.602453  0.646034  1.160233
19  0.575021  0.625694  0.693546      0.602453  0.602453  2.411898

In [15]:
# Apply function sub_sample (20%) 
train_df = sub_sample(0.2)
train_df

                                              id  label
101866  8312c9bac5ab0dded0b79b0e8793ac4470727f40      0
104382  146db8073ee4fc6e64dac8cc8b835306ce4f00a5      1
123473  d6bfa926359cdffe8a770c4c6513322924825928      1
201216  9e2bb84236b7adcd4d245dd6ac9d573bea10204b      0
62800   1809061f44efe7f494c72da733ba50f6a5f054c9      0
...                                          ...    ...
110944  18b62ca10f10a13b9dcab6c377a69e3afbb4f716      0
118348  74e880c6deb43c4d0a31adba76becb1eebfaa813      1
28330   f2552d8e74f0c4ccead7af168b9c3d5e2ce94bce      0
5173    112e7f5aff9bb19cfe15e8646ba6a5bcf7dbe4fd      0
45096   ac661b809ea7db639605d5302b692680f4c8c19f      1

[44005 rows x 2 columns]

In [16]:
# Apply function to_array()
train_set = to_array()
x_train = train_set[0]
y_train = train_set[1]

### Model 3

In [17]:
num_classes = 2
input_shape = (96, 96, 3)

model2 = keras.Sequential(
    [keras.Input(shape = input_shape),
     layers.Conv2D(filters = 32, kernel_size=(3,3),activation = 'sigmoid'),
     layers.MaxPooling2D(pool_size=(2, 2)),
     layers.Conv2D(64, kernel_size=(3, 3), activation="sigmoid"),
     layers.MaxPooling2D(pool_size=(2, 2)),
     layers.Flatten(),
     layers.Dense(num_classes, activation="softmax"),
    ]
    )
model2.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_3 (Conv2D)               │ (None, 94, 94, 32)     │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_3 (MaxPooling2D)  │ (None, 47, 47, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_4 (Conv2D)               │ (None, 45, 45, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_4 (MaxPooling2D)  │ (None, 22, 22, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_2 (Flatten)             │ (None, 30976)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 2)              │        61,954 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 81,346 (317.76 KB)

 Trainable params: 81,346 (317.76 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
# training model 3
batch_size = 200
epochs = 20

model2.compile(loss="categorical_crossentropy", optimizer="sgd", metrics=["accuracy", "auc"])

history2 = model2.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.1)

Epoch 1/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 8s 59ms/step - accuracy: 0.5298 - auc: 0.5405 - loss: 3.9475 - val_accuracy: 0.3975 - val_auc: 0.3390 - val_loss: 2.7819
Epoch 2/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.5693 - auc: 0.5758 - loss: 0.7947 - val_accuracy: 0.6025 - val_auc: 0.6069 - val_loss: 1.2657
Epoch 3/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.5944 - auc: 0.6009 - loss: 0.7093 - val_accuracy: 0.6025 - val_auc: 0.6302 - val_loss: 1.1668
Epoch 4/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.5999 - auc: 0.6030 - loss: 0.7023 - val_accuracy: 0.6025 - val_auc: 0.6707 - val_loss: 1.1526
Epoch 5/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 37ms/step - accuracy: 0.5926 - auc: 0.6006 - loss: 0.7032 - val_accuracy: 0.6025 - val_auc: 0.6558 - val_loss: 1.0803
Epoch 6/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.6041 - auc: 0.6163 - loss: 0.6909 - val_accuracy: 0.6025 - val_auc: 0.6464 - val_loss: 1.1681
Epoch 7/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.6001 - auc: 0.6301 - loss: 0.6953 - val_accuracy: 0.3975 - val_auc: 0.3725 - val_loss: 1.6336
Epoch 8/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.5884 - auc: 0.6138 - loss: 0.7134 - val_accuracy: 0.6025 - val_auc: 0.6215 - val_loss: 1.0966
Epoch 9/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.5972 - auc: 0.6422 - loss: 0.6828 - val_accuracy: 0.6025 - val_auc: 0.6310 - val_loss: 1.2051
Epoch 10/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.5959 - auc: 0.6424 - loss: 0.6813 - val_accuracy: 0.3975 - val_auc: 0.4827 - val_loss: 1.8133
Epoch 11/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.5796 - auc: 0.6356 - loss: 0.7001 - val_accuracy: 0.3975 - val_auc: 0.4017 - val_loss: 2.2121
Epoch 12/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.5748 - auc: 0.6252 - loss: 0.7306 - val_accuracy: 0.3975 - val_auc: 0.3909 - val_loss: 2.4491
Epoch 13/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 39ms/step - accuracy: 0.5893 - auc: 0.6295 - loss: 0.7459 - val_accuracy: 0.6025 - val_auc: 0.6369 - val_loss: 1.4153
Epoch 14/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.5731 - auc: 0.6401 - loss: 0.6900 - val_accuracy: 0.6025 - val_auc: 0.6410 - val_loss: 1.2203
Epoch 15/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.5991 - auc: 0.6563 - loss: 0.6733 - val_accuracy: 0.3975 - val_auc: 0.4569 - val_loss: 1.6725
Epoch 16/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.5682 - auc: 0.6256 - loss: 0.6951 - val_accuracy: 0.6025 - val_auc: 0.6415 - val_loss: 1.3436
Epoch 17/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.5839 - auc: 0.6547 - loss: 0.6696 - val_accuracy: 0.6025 - val_auc: 0.6278 - val_loss: 1.4883
Epoch 18/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.5933 - auc: 0.6646 - loss: 0.6579 - val_accuracy: 0.6025 - val_auc: 0.6474 - val_loss: 1.2725
Epoch 19/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.5900 - auc: 0.6562 - loss: 0.6662 - val_accuracy: 0.6025 - val_auc: 0.6420 - val_loss: 0.8820
Epoch 20/20
100/100 ━━━━━━━━━━━━━━━━━━━━ 4s 38ms/step - accuracy: 0.5788 - auc: 0.6481 - loss: 0.6458 - val_accuracy: 0.6025 - val_auc: 0.6434 - val_loss: 0.8374

In [19]:
# Model 3: Writing away the results 
write_away('Basic_CNN_20perc', history2.history, 'Basic_CNN_20perc.csv')

    accuracy       auc      loss  val_accuracy   val_auc  val_loss
0   0.538003  0.549295  1.862444      0.397547  0.338974  2.781864
1   0.580425  0.590821  0.706368      0.602453  0.606876  1.265699
2   0.590576  0.601318  0.684753      0.602453  0.630244  1.166794
3   0.599010  0.601818  0.682484      0.602453  0.670690  1.152603
4   0.593808  0.604799  0.680995      0.602453  0.655834  1.080333
5   0.599566  0.612951  0.676514      0.602453  0.646435  1.168056
6   0.598101  0.631015  0.673163      0.397547  0.372517  1.633631
7   0.596536  0.633414  0.672364      0.602453  0.621531  1.096624
8   0.592899  0.645974  0.661120      0.602453  0.631006  1.205126
9   0.593606  0.649369  0.655669      0.397547  0.482676  1.813294
10  0.598808  0.654749  0.657812      0.397547  0.401692  2.212125
11  0.580021  0.646819  0.658538      0.397547  0.390879  2.449054
12  0.611989  0.667679  0.662048      0.602453  0.636925  1.415325
13  0.578860  0.651072  0.648771      0.602453  0.640987  1.220252
14  0.598354  0.664594  0.645528      0.397547  0.456886  1.672483
15  0.578809  0.647749  0.648871      0.602453  0.641510  1.343578
16  0.581334  0.651895  0.645489      0.602453  0.627778  1.488279
17  0.584516  0.658499  0.639252      0.602453  0.647411  1.272524
18  0.580829  0.654108  0.640721      0.602453  0.642022  0.882002
19  0.577042  0.653262  0.633682      0.602453  0.643364  0.837367